### ISSUE TITLE
ts starter project contains unnecessary __tests__ folder given test match config

### ISSUE THREAD

**Issue by rob212** [joejag/starters#1]
The ts starter `main.spec.ts` test file currently resides in a `__tests__` directory. Given the jest test match configuration within the accompanying `package.json` file this is not required as Jest will detect any files that contain `.spec.` and `.test.`.

To make this consistent with the existing Node starter I suggest that the `main.spec.ts` file be placed alongside the supporting application code, the `__tests__` dir removed and the jest config amended to only allow for files containing the `.spec.` convention.

**Comment by joejag** [comment]
Resolved in #2
